drop TABLE permToAccount;

drop TABLE PERMISSION;
CREATE TABLE PERMISSION (
	nom VARCHAR(50) PRIMARY KEY NOT NULL
);

drop TABLE ACCOUNT;
CREATE TABLE ACCOUNT (
	username VARCHAR(20) PRIMARY KEY NOT NULL,
	password VARCHAR(50) NOT NULL
);


CREATE TABLE PERMTOACCOUNT (
	nom_permission VARCHAR(50) NOT NULL,
	username_account VARCHAR(20) NOT NULL,
	PRIMARY KEY(nom_permission, username_account),
	CONSTRAINT PERMTOACCOUNT_nom_permission FOREIGN KEY (nom_permission) REFERENCES PERMISSION(nom)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT PERMTOACCOUNT_username_account FOREIGN KEY (username_account) REFERENCES ACCOUNT(username)
	ON DELETE CASCADE ON UPDATE CASCADE
);