DROP TABLE ITEM_OF_FLUX_RSS;

DROP TABLE RSS_ITEM;
CREATE TABLE RSS_ITEM (
	id SERIAL PRIMARY KEY NOT NULL,
	title VARCHAR NOT NULL,
	link VARCHAR NOT NULL,
	pub_date TIMESTAMP,
	description VARCHAR,
	importance INTEGER NOT NULL DEFAULT 0
);

DROP TABLE FLUX_RSS;
CREATE TABLE FLUX_RSS (
	link VARCHAR PRIMARY KEY NOT NULL,
	id_last_rss INTEGER,
	CONSTRAINT FLUX_RSS_id_last_rss FOREIGN KEY (id_last_rss) REFERENCES RSS_ITEM(id)
	ON DELETE SET NULL
);


CREATE TABLE ITEM_OF_FLUX_RSS (
	link_flux_rss VARCHAR NOT NULL,
	id_rss_item INTEGER NOT NULL,
	PRIMARY KEY (link_flux_rss, id_rss_item),
	CONSTRAINT ITEM_OF_FLUX_RSS_link_flux_rss FOREIGN KEY (link_flux_rss) REFERENCES FLUX_RSS(link)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ITEM_OF_FLUX_RSS_id_rss_item FOREIGN KEY (id_rss_item) REFERENCES RSS_ITEM(id)
	ON DELETE CASCADE ON UPDATE CASCADE
);