drop TABLE permToAccount;

drop TABLE PERMISSION;
CREATE TABLE PERMISSION (
	nom VARCHAR(50) PRIMARY KEY NOT NULL
	ON DELETE CASCADE
   	ON UPDATE CASCADE
);

drop TABLE ACCOUNT;
CREATE TABLE ACCOUNT (
	username VARCHAR(20) PRIMARY KEY NOT NULL,
	password VARCHAR(50) NOT NULL,
	ON DELETE CASCADE
	ON UPDATE CASCADE
);


CREATE TABLE PERMTOACCOUNT (
	nom_permission VARCHAR(50) REFERENCES PERMISSION(nom) NOT NULL,
	username_account VARCHAR(20) REFERENCES ACCOUNT(username) NOT NULL,
	PRIMARY KEY(nom_permission, username_account)
)