-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');d
-- INSERT INTO PERMISSION VALUES('');


-- INSERT INTO ACCOUNT VALUES('user','userpwd');
INSERT INTO ACCOUNT VALUES('admin','adminpwd');