-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');
-- INSERT INTO PERMISSION VALUES('');


-- INSERT INTO ACCOUNT VALUES('user','userpwd');
INSERT INTO RSS_ITEM VALUES(id,title,link,pub_date,importance);
